### ISSUE TITLE
OMG THIS IS SOOO SAD

### ISSUE THREAD

**Issue by Balloogney** [SmokeyTheKat/clature#1]
"Fetal Error"
"Archie pel eggo"
Wehn will the egregious spellling misstakes ever stop?? :(

**Comment by SmokeyTheKat** [comment]
Yo donet evan now wht yo tlkn bout

**Comment by Balloogney** [comment]
Bud you spelled Assembly as Assebmly once ok. This is so tragic!

**Comment by Balloogney** [comment]
Ok, I'll let you off with a warning.
